Set CMAKE_OSX_ARCHITECTURES to x86_64 when build for x86_64-apple-darwin
Fixes build error on Apple Silicon cause cargo can't link universal
archive

```
error: failed to add native library
/Users/messense/Projects/liblbfgs-sys/target/x86_64-apple-darwin/debug/build/liblbfgs-sys-063cb5a2d3f695df/out/lib/liblbfgs.a:
file too small to be an archive
```